import React,{useEffect,useState} from "react";
import {Bell,Building2,Globe2,Save,Shield} from "lucide-react";
import {apiFetch} from "../lib/api";
type Settings={companyName:string;rfc:string;email:string;phone:string;city:string;country:string;systemNotifications:boolean;emailAlerts:boolean;overduePayments:boolean;upcomingRenewals:boolean;delayedProjects:boolean;newLeads:boolean;currency:string;timezone:string;language:string;dateFormat:string;sessionTimeout:number;twoFactor:boolean};
const defaults:Settings={companyName:"Designs Agency S.A. de C.V.",rfc:"DAG240115TJ1",email:"hola@designs.mx",phone:"+52 664 123 4567",city:"Tijuana, Baja California",country:"México",systemNotifications:true,emailAlerts:true,overduePayments:true,upcomingRenewals:true,delayedProjects:true,newLeads:true,currency:"MXN",timezone:"America/Tijuana",language:"es-MX",dateFormat:"DD/MM/YYYY",sessionTimeout:10,twoFactor:false};
const request=(method="GET",body?:Settings)=>apiFetch<{settings:Settings}>("/api/settings",{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});
const Field=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label><span className="mb-1 block text-[10px] font-bold uppercase text-[#58708f]">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="h-[34px] w-full rounded-lg border border-[#d8e0eb] bg-[#f8fafc] px-3 text-[11px] text-slate-800 outline-none focus:border-blue-500 focus:bg-white"/></label>;
const Toggle=({checked,onChange}:{checked:boolean;onChange:(v:boolean)=>void})=><button type="button" onClick={()=>onChange(!checked)} className={`relative h-[14px] w-[21px] rounded-full border-2 ${checked?"border-blue-600 bg-blue-600":"border-slate-300 bg-slate-300"}`}><i className={`absolute top-[1px] h-[8px] w-[8px] rounded-full bg-white transition-all ${checked?"left-[9px]":"left-[1px]"}`}/></button>;
export default function CRMSettings(){const [s,setS]=useState(defaults),[saved,setSaved]=useState(false);useEffect(()=>{request().then(r=>setS({...defaults,...r.settings})).catch(()=>{})},[]);const set=<K extends keyof Settings>(k:K,v:Settings[K])=>setS(x=>({...x,[k]:v}));const save=async()=>{await request("PUT",s);setSaved(true);setTimeout(()=>setSaved(false),1800)};
return <form onSubmit={e=>{e.preventDefault();void save()}} className="-mt-1 grid grid-cols-1 gap-3 text-left text-[11px] animate-fade-in xl:grid-cols-[2fr_1fr]">
 <div className="space-y-3"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 text-xs font-bold"><Building2 className="h-4 w-4 text-blue-600"/>Información de la empresa</h2><div className="grid grid-cols-1 gap-x-3 gap-y-3 sm:grid-cols-2"><Field label="Nombre empresa" value={s.companyName} onChange={v=>set("companyName",v)}/><Field label="RFC" value={s.rfc} onChange={v=>set("rfc",v)}/><Field label="Correo corporativo" value={s.email} onChange={v=>set("email",v)}/><Field label="Teléfono" value={s.phone} onChange={v=>set("phone",v)}/><Field label="Ciudad" value={s.city} onChange={v=>set("city",v)}/><Field label="País" value={s.country} onChange={v=>set("country",v)}/></div></section>
 <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 text-xs font-bold"><Shield className="h-4 w-4 text-blue-600"/>Seguridad y sesión</h2><p className="mb-2 text-[10px] font-bold uppercase text-[#58708f]">Tiempo de inactividad antes de cerrar sesión</p><div className="flex items-center gap-3"><input type="range" min="5" max="60" step="5" value={s.sessionTimeout} onChange={e=>set("sessionTimeout",Number(e.target.value))} className="crm-progress w-full accent-blue-600"/><b className="flex h-12 w-14 items-center justify-center rounded-lg border border-blue-200 bg-blue-50 text-center text-blue-700">{s.sessionTimeout}<br/>min</b></div><p className="mt-1 text-[10px] text-[#91a0bd]">La sesión cerrará automáticamente tras {s.sessionTimeout} minutos sin actividad. Se mostrará aviso con 2 minutos de anticipación.</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><div><b className="block text-xs">Autenticación de dos factores</b><span className="text-[10px] text-[#91a0bd]">Añade una capa extra de seguridad al inicio de sesión</span></div><button type="button" onClick={()=>set("twoFactor",!s.twoFactor)} className={`rounded-lg border px-3 py-1.5 font-semibold ${s.twoFactor?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-slate-200"}`}>{s.twoFactor?"2FA configurado":"Configurar 2FA"}</button></div></section></div>
 <div className="space-y-3"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 text-xs font-bold"><Bell className="h-4 w-4 text-blue-600"/>Notificaciones</h2>{[["Notificaciones en sistema","systemNotifications"],["Alertas por correo","emailAlerts"]].map(([label,key])=><div key={key} className="flex h-12 items-center justify-between border-b border-slate-100 text-slate-600"><span>{label}</span><Toggle checked={s[key as keyof Settings] as boolean} onChange={v=>set(key as keyof Settings,v as never)}/></div>)}<p className="mb-2 mt-4 text-[10px] font-bold uppercase text-[#58708f]">Alertas activas</p>{[["Pagos vencidos","overduePayments"],["Renovaciones próximas","upcomingRenewals"],["Proyectos atrasados","delayedProjects"],["Nuevos prospectos","newLeads"]].map(([label,key])=><label key={key} className="mb-2 flex items-center gap-2 text-[#58708f]"><input type="checkbox" checked={s[key as keyof Settings] as boolean} onChange={e=>set(key as keyof Settings,e.target.checked as never)} className="h-3.5 w-3.5 accent-blue-600"/>{label}</label>)}</section>
 <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 text-xs font-bold"><Globe2 className="h-4 w-4 text-blue-600"/>Preferencias</h2>{[["Moneda","currency",[["MXN","MXN – Peso Mexicano"],["USD","USD – Dólar estadounidense"]]],["Zona horaria","timezone",[["America/Tijuana","America/Tijuana (UTC-7)"],["America/Mexico_City","America/México City (UTC-6)"]]],["Idioma","language",[["es-MX","Español (México)"],["en-US","English (US)"]]],["Formato fecha","dateFormat",[["DD/MM/YYYY","DD/MM/YYYY"],["MM/DD/YYYY","MM/DD/YYYY"]]]].map(([label,key,options]:any)=><label key={key} className="mb-3 block"><span className="mb-1 block text-[10px] font-bold uppercase text-[#58708f]">{label}</span><select value={s[key as keyof Settings] as string} onChange={e=>set(key as keyof Settings,e.target.value as never)} className="h-[35px] w-full rounded-lg border border-[#d8e0eb] bg-[#f8fafc] px-3 text-[11px]">{options.map(([v,l]:string[])=><option key={v} value={v}>{l}</option>)}</select></label>)}</section><div className="flex justify-end"><button className="flex items-center gap-2 rounded-xl bg-[#2463eb] px-5 py-2.5 font-bold text-white shadow-sm"><Save className="h-4 w-4"/>{saved?"Cambios guardados":"Guardar cambios"}</button></div></div>
 </form>}
