import React, { useEffect, useMemo, useState } from "react";
import { CheckCircle2, CircleX, Eye, Pencil, Plus, Shield, Trash2, X } from "lucide-react";
import { apiFetch } from "../lib/api";

type UserItem={username:string;name:string;email:string;role:string;area:string;status:"Activo"|"Bloqueado";initials:string};
type Role={name:string;color:string;owner:string};
const roles:Role[]=[{name:"Admin General",color:"#2463eb",owner:"Adriana"},{name:"Administración",color:"#00b981",owner:"Jorge"},{name:"Gerente Dev",color:"#8557f5",owner:"Carlos"},{name:"Gerente Web",color:"#f59e0b",owner:"Sofía"}];
const modules=["Dashboard","Clientes","Prospectos","Servicios","Pagos","Renovaciones","Cotizaciones","Proyectos Dev","Proyectos Web","Kanban","Tareas","Personal","Credenciales","Reportes","Usuarios","Configuración"];
const permission:Record<string,string[]>={
  "Admin General":modules,
  "Administración":["Dashboard","Clientes","Prospectos","Servicios","Pagos","Renovaciones","Cotizaciones","Kanban","Tareas","Reportes"],
  "Gerente Dev":["Dashboard","Clientes","Cotizaciones","Proyectos Dev","Kanban","Tareas","Personal"],
  "Gerente Web":["Dashboard","Clientes","Cotizaciones","Proyectos Web","Kanban","Tareas","Personal"],
};
const fallback:UserItem[]=[
 {username:"adriana",name:"Adriana García López",email:"adriana@designs.mx",role:"Admin General",area:"Dirección",status:"Activo",initials:"AG"},
 {username:"jorge",name:"Jorge Ramírez Acosta",email:"jorge@designs.mx",role:"Administración",area:"Administración",status:"Activo",initials:"JR"},
 {username:"carlos",name:"Carlos Mendoza Ruiz",email:"carlos@designs.mx",role:"Gerente Dev",area:"Desarrollo",status:"Activo",initials:"CM"},
 {username:"sofia",name:"Sofía Rodríguez Vega",email:"sofia@designs.mx",role:"Gerente Web",area:"Páginas web",status:"Activo",initials:"SR"},
];
const api=(url:string,init?:RequestInit)=>apiFetch<any>(url,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("figma_session")||""}`,...init?.headers}});

export default function CRMUsers(){
 const [users,setUsers]=useState<UserItem[]>(fallback),[modal,setModal]=useState(false),[error,setError]=useState("");
 const emptyForm={firstName:"",lastName:"",email:"",password:"",role:"Administración",area:"Administración",status:"Activo"};
 const [form,setForm]=useState(emptyForm);
 const load=()=>api("/api/users").then(r=>setUsers(r.users)).catch(()=>{});
 useEffect(()=>{ void load(); },[]);
 const counts=useMemo(()=>Object.fromEntries(roles.map(r=>[r.name,users.filter(u=>u.role===r.name).length])),[users]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setError("");const username=form.email.split("@")[0].trim().toLowerCase();try{await api("/api/users",{method:"POST",body:JSON.stringify({...form,username,name:`${form.firstName} ${form.lastName}`.trim()})});setModal(false);setForm(emptyForm);load()}catch(e){setError(e instanceof Error?e.message:"No se pudo crear")}};
 const toggle=async(u:UserItem)=>{if(u.username==="adriana")return;await api(`/api/users/${u.username}`,{method:"PUT",body:JSON.stringify({status:u.status==="Activo"?"Bloqueado":"Activo"})});load()};
 const remove=async(u:UserItem)=>{if(u.username==="adriana"||!confirm(`¿Eliminar a ${u.name}?`))return;await api(`/api/users/${u.username}`,{method:"DELETE"});load()};
 return <div className="-mt-1 space-y-4 text-left animate-fade-in text-[11px]">
  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">{roles.map(r=><section key={r.name} className="h-[124px] rounded-xl border border-slate-200 bg-white p-3.5 shadow-sm"><div className="flex h-8 w-8 items-center justify-center rounded-lg" style={{color:r.color,background:`${r.color}12`}}><Shield className="h-4 w-4"/></div><h2 className="mt-2 font-bold text-slate-900">{r.name}</h2><p className="mt-1 text-[#91a0bd]">{r.owner}</p><p className="mt-1 font-semibold" style={{color:r.color}}>{counts[r.name]||0} usuario{counts[r.name]===1?"":"s"}</p></section>)}</div>
  <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><header className="flex h-[53px] items-center justify-between px-4"><b className="text-xs">Directorio de usuarios</b><button onClick={()=>setModal(true)} className="flex items-center gap-1 rounded-lg bg-[#2463eb] px-4 py-2 font-bold text-white"><Plus className="h-3.5 w-3.5"/>Nuevo usuario</button></header><div className="overflow-x-auto"><table className="w-full min-w-[1050px]"><thead className="h-9 bg-[#f6f8fb] text-left text-[10px] uppercase text-[#58708f]"><tr>{["Usuario","Correo","Contraseña","Rol","Área","Estado","Acciones"].map(x=><th className="px-3 font-semibold" key={x}>{x}</th>)}</tr></thead><tbody>{users.map((u,i)=>{const r=roles.find(x=>x.name===u.role)||roles[0];return <tr className="h-[46px] border-t border-slate-100" key={u.username}><td className="px-3"><div className="flex items-center gap-2"><i className="flex h-6 w-6 items-center justify-center rounded-full text-[9px] not-italic font-bold text-white" style={{background:r.color}}>{u.initials}</i><b>{u.name}</b></div></td><td className="px-3 font-mono text-[#58708f]">{u.email}</td><td className="px-3 font-mono tracking-[2px] text-[#91a0bd]">•••••••• <Eye className="inline h-3 w-3"/></td><td className="px-3"><span className="rounded-full px-2 py-1 font-semibold" style={{color:r.color,background:`${r.color}12`}}>{u.role}</span></td><td className="px-3 text-[#58708f]">{u.area}</td><td className="px-3"><span className={`rounded-full border px-2 py-1 ${u.status==="Activo"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-rose-200 bg-rose-50 text-rose-600"}`}>{u.status}</span></td><td className="px-3"><button className="p-1 text-blue-500"><Pencil className="h-3.5 w-3.5"/></button><button onClick={()=>toggle(u)} className="p-1 text-amber-500"><CircleX className="h-3.5 w-3.5"/></button><button onClick={()=>remove(u)} className="p-1 text-rose-500"><Trash2 className="h-3.5 w-3.5"/></button></td></tr>})}</tbody></table></div></section>
  <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><h2 className="h-10 px-4 pt-3 text-xs font-bold">Matriz de permisos por rol</h2><div className="overflow-x-auto"><table className="w-full min-w-[850px]"><thead className="h-9 bg-[#f6f8fb] text-left text-[10px] uppercase text-[#58708f]"><tr><th className="px-4">Módulo</th>{roles.map(r=><th key={r.name} className="text-center normal-case" style={{color:r.color}}>{r.name}</th>)}</tr></thead><tbody>{modules.map(m=><tr key={m} className="h-[34px] border-t border-slate-100"><td className="px-4 font-semibold">{m}</td>{roles.map(r=><td key={r.name} className="text-center">{permission[r.name].includes(m)?<CheckCircle2 className="mx-auto h-3.5 w-3.5 text-emerald-500"/>:<CircleX className="mx-auto h-3.5 w-3.5 text-slate-200"/>}</td>)}</tr>)}</tbody></table></div></section>
  {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#17233b]/60 p-4 backdrop-blur-[3px] animate-fade-in"><form onSubmit={create} className="w-full max-w-[448px] overflow-hidden rounded-[14px] bg-white shadow-[0_28px_70px_rgba(15,23,42,.35)] animate-scale-up">
   <header className="flex h-[54px] items-center justify-between border-b border-slate-100 px-5"><b className="text-[13px] text-slate-800">Nuevo usuario</b><button type="button" onClick={()=>setModal(false)} className="text-slate-400 hover:text-slate-700"><X className="h-4 w-4"/></button></header>
   <div className="px-5 py-5"><div className="grid grid-cols-2 gap-x-3 gap-y-4">
    <label><span className="mb-1 block text-[10px] font-bold uppercase text-[#58708f]">Nombre *</span><input autoFocus required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} placeholder="Nombre" className="h-[35px] w-full rounded-lg border border-[#d8e0eb] bg-[#f8fafc] px-3 text-[11px] outline-none placeholder:text-slate-400 focus:border-blue-500 focus:bg-white"/></label>
    <label><span className="mb-1 block text-[10px] font-bold uppercase text-[#58708f]">Apellido</span><input value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} placeholder="Apellidos" className="h-[35px] w-full rounded-lg border border-[#d8e0eb] bg-[#f8fafc] px-3 text-[11px] outline-none placeholder:text-slate-400 focus:border-blue-500 focus:bg-white"/></label>
    <label><span className="mb-1 block text-[10px] font-bold uppercase text-[#58708f]">Correo *</span><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="usuario@designs.mx" className="h-[35px] w-full rounded-lg border border-[#d8e0eb] bg-[#f8fafc] px-3 text-[11px] outline-none placeholder:text-slate-400 focus:border-blue-500 focus:bg-white"/></label>
    <label><span className="mb-1 block text-[10px] font-bold uppercase text-[#58708f]">Contraseña</span><input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Mínimo 8 caracteres" className="h-[35px] w-full rounded-lg border border-[#d8e0eb] bg-[#f8fafc] px-3 text-[11px] outline-none placeholder:text-slate-400 focus:border-blue-500 focus:bg-white"/></label>
   </div><div className="mt-4 grid grid-cols-3 gap-3">
    <label><span className="mb-1 block text-[10px] font-bold uppercase text-[#58708f]">Rol</span><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="h-[35px] w-full rounded-lg border border-[#d8e0eb] bg-[#f8fafc] px-2 text-[11px] text-slate-700 outline-none">{roles.map(r=><option key={r.name}>{r.name}</option>)}</select></label>
    <label><span className="mb-1 block text-[10px] font-bold uppercase text-[#58708f]">Área</span><select value={form.area} onChange={e=>setForm({...form,area:e.target.value})} className="h-[35px] w-full rounded-lg border border-[#d8e0eb] bg-[#f8fafc] px-2 text-[11px] text-slate-700 outline-none"><option>Administración</option><option>Dirección</option><option>Desarrollo</option><option>Páginas web</option></select></label>
    <label><span className="mb-1 block text-[10px] font-bold uppercase text-[#58708f]">Estado</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="h-[35px] w-full rounded-lg border border-[#d8e0eb] bg-[#f8fafc] px-2 text-[11px] text-slate-700 outline-none"><option value="Activo">Activo</option><option value="Bloqueado">Bloqueado</option></select></label>
   </div>{error&&<p className="mt-3 text-[10px] font-semibold text-rose-500">{error}</p>}</div>
   <footer className="flex h-[62px] items-center justify-end gap-2 border-t border-slate-100 px-5"><button type="button" onClick={()=>setModal(false)} className="h-[34px] rounded-lg border border-slate-200 px-4 font-semibold text-slate-600 hover:bg-slate-50">Cancelar</button><button className="h-[34px] rounded-lg bg-[#2463eb] px-4 font-bold text-white shadow-sm hover:bg-blue-700">Crear usuario</button></footer>
  </form></div>}
 </div>
}
